### ISSUE TITLE
path issue for retraining

### ISSUE THREAD

**Issue by Ha-JH** [jhwangbo/ME491_2022_project#5]
there seems to be path error when running runner.py in retrain mode:

hajh@hydra:~/Workspace/raisim_ws/ME491_2022_project/raisimGymME491/env/envs/aliengo_jump$ python runner.py --mode retrain --weight data/ME491_final_project/2022-11-23-19-03-43/full_2620.pt
[RAISIM_GYM] Tensorboard session created: http://localhost:6007/

Retraining from the checkpoint: data/ME491_final_project/2022-11-23-19-03-43/full_2620.pt

Traceback (most recent call last):
  File "/home/hajh/Workspace/raisim_ws/ME491_2022_project/raisimGymME491/env/envs/aliengo_jump/runner.py", line 81, in <module>
    load_param(weight_path, env, actor, critic, ppo.optimizer, saver.data_dir)
  File "/home/hajh/Workspace/raisim_ws/ME491_2022_project/raisimGymME491/helper/raisim_gym_helper.py", line 50, in load_param
    copyfile(item_to_save, pretrained_data_dir+'/'+item_to_save.rsplit('/', 1)[1])
  File "/home/hajh/anaconda3/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'data/ME491_final_project/2022-11-23-19-03-43/full_2620.pt'

**Comment by jhwangbo** [comment]
You have to pass the full path to the pt file, not from ``data``
