### ISSUE TITLE
python setup.py develop ERROR

### ISSUE THREAD

**Issue by alswns314** [jhwangbo/ME491_2022_project#7]
when I ran "python setup.py develop python setup.py develop --CMAKE_PREFIX_PATH home/minjun/Projects/RAISIM/raisimLib/raisim/linux/" in terminal, an error came out.

(raisim) minjun@minjun:~/Projects/ME491_2022_project$ python setup.py develop --CMAKE_PREFIX_PATH /home/minjun/Projects/RAISIM/raisimLib/raisim/linux/
running develop
/home/minjun/anaconda3/envs/raisim/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/minjun/anaconda3/envs/raisim/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing raisim_gym_torch.egg-info/PKG-INFO
writing dependency_links to raisim_gym_torch.egg-info/dependency_links.txt
writing requirements to raisim_gym_torch.egg-info/requires.txt
writing top-level names to raisim_gym_torch.egg-info/top_level.txt
reading manifest file 'raisim_gym_torch.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'raisim_gym_torch.egg-info/SOURCES.txt'
running build_ext
-- pybind11 v2.9.0 
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
CMake Error at CMakeLists.txt:71 (find_package):
  Could not find a package configuration file provided by "raisim" with any
  of the following names:

    raisimConfig.cmake
    raisim-config.cmake

  Add the installation prefix of "raisim" to CMAKE_PREFIX_PATH or set
  "raisim_DIR" to a directory containing one of the above files.  If "raisim"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/minjun/Projects/ME491_2022_project/build/temp.linux-x86_64-cpython-310/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "/home/minjun/Projects/ME491_2022_project/setup.py", line 68, in <module>
    setup(
  File "/home/minjun/anaconda3/envs/raisim/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/minjun/anaconda3/envs/raisim/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/minjun/anaconda3/envs/raisim/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/minjun/anaconda3/envs/raisim/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/minjun/anaconda3/envs/raisim/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/minjun/anaconda3/envs/raisim/lib/python3.10/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/minjun/anaconda3/envs/raisim/lib/python3.10/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/home/minjun/anaconda3/envs/raisim/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/minjun/anaconda3/envs/raisim/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/minjun/anaconda3/envs/raisim/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/minjun/Projects/ME491_2022_project/setup.py", line 38, in run
    self.build_extension(ext)
  File "/home/minjun/Projects/ME491_2022_project/setup.py", line 65, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/minjun/anaconda3/envs/raisim/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/minjun/Projects/ME491_2022_project', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/minjun/Projects/ME491_2022_project', '-DPYTHON_EXECUTABLE=/home/minjun/anaconda3/envs/raisim/bin/python', '-DCMAKE_PREFIX_PATH=/home/minjun/Projects/RAISIM/raisimLib/raisim/linux/', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

**Comment by jhwangbo** [comment]
Is this a typo ``when I ran "python setup.py develop python setup.py develop --CMAKE_PREFIX_PATH home/minjun/Projects/RAISIM/raisimLib/raisim/linux/" in terminal, an error came out.``?

If not check if you have entered the correct directory.  type ``cd home/minjun/Projects/RAISIM/raisimLib/raisim/linux/`` and check if the directory really exists.
